"""empty message

Revision ID: ad462566ece8
Revises: a18fb45922c5
Create Date: 2018-08-20 22:57:54.287214

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad462566ece8'
down_revision = 'a18fb45922c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.drop_column('question', 'creat_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('creat_time', mysql.DATETIME(), nullable=True))
    op.drop_column('question', 'create_time')
    # ### end Alembic commands ###
